# Generated by Django 4.2.23 on 2025-07-23 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='certification',
            name='related_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_blogs', to='portfolio.blog'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_blogs', to='portfolio.blog'),
        ),
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experiences/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='related_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_blogs', to='portfolio.blog'),
        ),
        migrations.AddField(
            model_name='myproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myprojects/'),
        ),
        migrations.AddField(
            model_name='myproject',
            name='related_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_blogs', to='portfolio.blog'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skill_icons/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='related_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_blogs', to='portfolio.blog'),
        ),
        migrations.AddField(
            model_name='workinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workinformation/'),
        ),
        migrations.AddField(
            model_name='workinformation',
            name='related_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workinfo_blogs', to='portfolio.blog'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolio.blog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
