name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up LFTP
        run: sudo apt-get install -y lftp

      - name: List files for debugging
        run: ls -l

      - name: Deploy to FTP
        run: |
          chmod +x deploy.sh
          ./deploy.sh ${{ secrets.FTP_HOST }} ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }} ./ /home/geoneerc/dineshportfolio.geoneer.com.np/cicd
